// Mock data for initial display before real data exists

export const mockProjects = [
  {
    id: "1",
    title: "DevBoard — Real-time Dashboard",
    description: "A collaborative developer dashboard with real-time metrics, CI/CD pipeline monitoring, and team analytics.",
    techStack: ["React", "TypeScript", "WebSocket", "D3.js"],
    demoUrl: "#",
    sourceUrl: "#",
    authorName: "Alex Chen",
    isFeatured: true,
  },
  {
    id: "2",
    title: "CodeSnap — Code Screenshot Tool",
    description: "Beautiful code screenshots with syntax highlighting, custom themes, and social sharing.",
    techStack: ["Next.js", "Canvas API", "Tailwind"],
    authorName: "Sarah Kim",
    isFeatured: false,
  },
  {
    id: "3",
    title: "APIForge — API Testing Suite",
    description: "Modern API testing platform with collections, environments, and automated test runners.",
    techStack: ["Electron", "React", "Node.js"],
    authorName: "Marcus Jones",
    isFeatured: true,
  },
  {
    id: "4",
    title: "GitFlow — Visual Git Client",
    description: "Intuitive visual git client with branch visualization, merge conflict resolution, and team workflows.",
    techStack: ["Rust", "Tauri", "Svelte"],
    authorName: "Priya Patel",
    isFeatured: false,
  },
  {
    id: "5",
    title: "Synthwave — Music Visualizer",
    description: "Audio-reactive visualizations with WebGL shaders and real-time FFT analysis.",
    techStack: ["WebGL", "Three.js", "Web Audio"],
    authorName: "Leo Zhang",
    isFeatured: false,
  },
  {
    id: "6",
    title: "DocuMind — AI Doc Generator",
    description: "AI-powered documentation generator that reads your codebase and creates comprehensive docs.",
    techStack: ["Python", "GPT-4", "Markdown"],
    authorName: "Nina Volkov",
    isFeatured: true,
  },
];

export const mockBlogs = [
  {
    id: "1",
    title: "Building Scalable Microservices with Event-Driven Architecture",
    excerpt: "Learn how event-driven patterns can transform your microservices into a resilient, scalable system.",
    tags: ["Architecture", "Backend", "Microservices"],
    authorName: "Alex Chen",
    readingTime: 8,
    createdAt: "2026-02-10",
  },
  {
    id: "2",
    title: "The Future of WebAssembly in Frontend Development",
    excerpt: "Exploring how WASM is changing the performance landscape of web applications.",
    tags: ["WebAssembly", "Performance", "Frontend"],
    authorName: "Sarah Kim",
    readingTime: 6,
    createdAt: "2026-02-08",
  },
  {
    id: "3",
    title: "Designing Developer-First APIs That People Love",
    excerpt: "A comprehensive guide to API design principles that prioritize developer experience.",
    tags: ["API Design", "DX", "REST"],
    authorName: "Marcus Jones",
    readingTime: 10,
    createdAt: "2026-02-05",
  },
  {
    id: "4",
    title: "From Burnout to Balance: A Developer's Journey",
    excerpt: "Personal reflections on managing burnout and finding sustainable productivity in tech.",
    tags: ["Career", "Wellness", "Productivity"],
    authorName: "Priya Patel",
    readingTime: 5,
    createdAt: "2026-02-01",
  },
];

export const mockDevelopers = [
  {
    id: "1",
    fullName: "Alex Chen",
    username: "alexchen",
    title: "Full-Stack Engineer",
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    githubUrl: "#",
    linkedinUrl: "#",
  },
  {
    id: "2",
    fullName: "Sarah Kim",
    username: "sarahkim",
    title: "Frontend Architect",
    skills: ["Vue", "React", "WebGL", "Design Systems"],
    githubUrl: "#",
    twitterUrl: "#",
  },
  {
    id: "3",
    fullName: "Marcus Jones",
    username: "marcusj",
    title: "Backend Engineer",
    skills: ["Go", "Rust", "PostgreSQL", "gRPC"],
    githubUrl: "#",
    linkedinUrl: "#",
  },
  {
    id: "4",
    fullName: "Priya Patel",
    username: "priyap",
    title: "DevOps Lead",
    skills: ["Kubernetes", "Terraform", "CI/CD", "Python"],
    githubUrl: "#",
    websiteUrl: "#",
  },
  {
    id: "5",
    fullName: "Leo Zhang",
    username: "leozhang",
    title: "Creative Developer",
    skills: ["Three.js", "WebGL", "Shaders", "Canvas"],
    githubUrl: "#",
    twitterUrl: "#",
  },
  {
    id: "6",
    fullName: "Nina Volkov",
    username: "ninavolkov",
    title: "ML Engineer",
    skills: ["Python", "PyTorch", "NLP", "MLOps"],
    githubUrl: "#",
    linkedinUrl: "#",
  },
];

export const stats = [
  { label: "Developers", value: "120+" },
  { label: "Projects", value: "350+" },
  { label: "Blog Posts", value: "200+" },
  { label: "Technologies", value: "50+" },
];
